import fs from 'node:fs';
import path from 'node:path';

const apiUrl = String(process.env.KASHORIA_API_URL || '').trim().replace(/\/+$/, '');
if (!apiUrl) {
  console.warn('\nWARNING: KASHORIA_API_URL is not set. Netlify frontend will not be able to reach the backend until you set it in Netlify environment variables and redeploy.\n');
}

const configPath = path.resolve('netlify-site/js/config.js');
const safe = JSON.stringify(apiUrl);
const config = `/* Generated by Netlify build. Do not edit this file manually. */\nwindow.KASHORIA_API = ${safe};\nwindow.KASHORIA_CONFIG = Object.assign({\n  freeShippingAt: 1299,\n  shippingFee: 80,\n  giftWrapFee: 40,\n  whatsapp: '917778975203',\n  instagram: 'https://www.instagram.com/kashoria_/'\n}, window.KASHORIA_CONFIG || {});\n`;
fs.writeFileSync(configPath, config);
console.log(`KASHORIA frontend configured for API: ${apiUrl || '(not set)'}`);
